Pflichtenheft Shareloc
======================
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 3, 12.04.2016
:toc:

= Auftrag
Erstellung einer Webapplikation. Eine Social Media Plattform, welche es einem ermöglicht reale Orte online zu erstellen, sodass sie für jeden sichtbar sind.
An einem Ort können Events erstellt werden, damit der User immer sieht was an diesem Ort passiert und ob er dorthin gehen möchte.

== Anforderungen
.Kompatibilität
* Die Applikation muss auf den unten aufgelisteten Browsern schön aussehen und voll funktionsfähig sein.
  - Google Chrome
  - Microsoft Edge
  - Mozilla Firefox

.Umsetzung
* Datenbank
  - MsSQL
  - Normalform 3
* Programmiersprachen
  - JavaScript (jQuery, Ajax)
  - PHP 7.0
  - HTML 5
* MVC
  - Model, View und Controller sinnvoll voneinander trennen
* OOP (Objekt orientiertes Programmieren)
  - Eigene Klassen
  - Eigene Funktion

.Design
* Durchgehende Designvorlage an die sich gehalten wird
* Modernes aber funktionales Design

= Hauptfunktionen
== Orte
Ein Ort ist eine in der Realität existierende Lokation. Dieser Ort kann der User, wenn er sich auf der Website registriert hat oder eingeloggt ist,
online erstellen. Dazu benötigt er die Koordinaten, einen Namen und eine Beschreibung. Ein Bild ist erwünscht aber nicht Pflicht. Es muss aber die
Möglichkeit bestehen ein Bild zu einem Ort hochzuladen, zudem kann ein Ort mehrere Bilder besitzen. Der Ort bildet die Grundlage für spätere Events,
welche auf ihm erstellte werden können. Ein Ort kann vom Ersteller später dann auch editiert werden (Bilder hochladen, Name ändern, Bilder löschen,
Beschreibung ändern), natürlich kann er den Ort auch komplett löschen. Nur der Ersteller kann den Ort editieren und löschen! Alle Orte werden auf einer
zusätzlichen Seite dargestellt. Sie werden in einer Scroll liste präsentiert. Der Name, die Beschreibung und die Bilder werden angezeigt, wenn es mehrere
Bilder sind werden sie in einem Slider zusammengefasst.

.Anforderungen Orte
* Angaben
  - Koordinaten (Pflichtangabe)
  - Name (Pflichtangabe)
  - Beschreibung (Pflichtangabe)
  - Bilder
* Bilder
  - Formate: JPG und PNG
  - automatische Skalierung auf der Website
* Editierung
  - Name
  - Beschreibung
  - Bilder
  - komplette Löschung
* Rechte
 - nur der Ersteller kann editieren
 - jeder kann Events auf dem Ort erstellen

.Vorbedingungen
* Der User muss eingeloggt sein
* Filterung nach Name

.Darstellung
* Eine Scroll-Liste mit allen Orten und Angaben zu den Orten (Unendliches Scroll)
* Angaben
 - Name
 - Beschreibung
 - Bilder in Slider

== Events
Ein Event kann fast alles sein, die einzige Bedingung ist, dass er auf einem Ort erstellt wird beziehungsweise dort stattfindet. An einem Ort können mehrere
Events gleichzeitig stattfinden. Jeder kann diese Events erstellen und ansehen. Der Event hat die Eingabefelder: Name, Beschreibung und der Ort, an welchem der Event
stattfindet. Ein Event kann nicht mehr editiert werden aber vom Ersteller gelöscht werden. Ein Event ist temporär, im Gegensatz zum Ort der dauerhaft ist.
Events sollen dem User mitteilen was am Ort gerade passiert oder wer gerade dort ist. Wenn in der Ortdarstellung auf einen Ort geklickt wird, werden alle Events
mit Angaben aufgeklappt. Bei erneutem klicken werden die Events wieder eingeklappt. Es werden der Name und die Beschreibung dargestellt.


.Anforderungen Events
* Angaben
  - Name (Pflichtangabe)
  - Beschreibung (Pflichtangabe)
  - Ort (Pflichtfeld)
* Editierung
  - komplette Löschung
* Rechte
 - jeder kann den Event sehen
 - jeder kann einen Event

.Vorbedingungen
* Der User muss eingeloggt sein
* Ein Ort muss erstellt sein oder ausgewählt werden

.Darstellung
* Events werden zusammen mit den Orten dargestellt
* Wenn man auf einen Ort klickt werden die zugehörigen Events angezeigt
* Angaben
 - Name
 - Beschreibung

== Login/Registrierung
Ein User muss sich, um Zugriff auf die Features der Seite zu bekommen, registrieren oder einloggen. Um sich registrieren zu können muss der User folgende
Angaben bereitstellen: Benutzername, Name, E-Mail und Passwort. Nach dem registrieren wird er direkt eingeloggt. Der User kann für zusätzliche Sicherheit
Google Two Way Authentication aktivieren. Wenn er dies tut muss er beim Einloggen einen zusätzlichen Code eingeben, diesen bekommt er per App die von Google
bereitgestellt wird. Wenn der User eingeloggt ist soll er sich ausloggen können. Wenn der User bereits registriert ist, kann er sich über seinen Benutzernamen
und sein Passwort einloggen. Alle eingetragenen Angaben sollen zu einem späteren Zeitpunkt editierbar sein.

.Anforderungen Registrierung
* Angaben
  - Name (Pflichtangabe)
  - E-Mail (Pflichtangabe)
  - Passwort (Pflichtangabe)
  - Benutzername (Pflichtangabe)
  - Google Two Way
* Darstellung
- Die Registrierung soll in einem Formular dargestellt werden.

.Anforderungen Login
* Angaben
  - Benutzername (Pflichtangabe)
  - Passwort (Pflichtangabe)
  - Google Two Way
* Vorbedingungen
 - Registriert
* Darstellung
- Als Formular

.Editierung
* Editierbare Angaben
  - Name
  - E-Mail
  - Passwort
  - Benutzername
  - Google Two Way
 * Rechte
 - nur der Account Ersteller kann diese editieren